-- MySQL Script generated by MySQL Workbench
-- Sun May  5 13:18:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema popollo_adventure
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema popollo_adventure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `popollo_adventure` DEFAULT CHARACTER SET utf8 ;
USE `popollo_adventure` ;

-- -----------------------------------------------------
-- Table `popollo_adventure`.`Heroe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `popollo_adventure`.`Heroe` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `saludMaxima` INT NULL,
  `salud` INT NULL,
  `manaMaximo` INT NULL,
  `mana` INT NULL,
  `fuerza` INT NULL,
  `magia` INT NULL,
  `agilidad` INT NULL,
  `defensa` INT NULL,
  `dinero` INT NULL,
  `reputacion` INT NULL,
  `experiencia` INT NULL,
  `nivel` INT NULL,
  `explorar` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popollo_adventure`.`Objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `popollo_adventure`.`Objeto` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `poder` INT NULL,
  `cantidad` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `precio` INT NULL,
  `Heroe_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Objeto_Heroe1_idx` (`Heroe_ID` ASC),
  CONSTRAINT `fk_Objeto_Heroe1`
    FOREIGN KEY (`Heroe_ID`)
    REFERENCES `popollo_adventure`.`Heroe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popollo_adventure`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `popollo_adventure`.`Habilidad` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `especial` INT NULL,
  `manaUtilizado` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `Heroe_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Habilidad_Heroe_idx` (`Heroe_ID` ASC),
  CONSTRAINT `fk_Habilidad_Heroe`
    FOREIGN KEY (`Heroe_ID`)
    REFERENCES `popollo_adventure`.`Heroe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Introducir datos
-- Heroe
insert into heroe values(
	1,
	'Popollo',
    'Un adorable popollito comilon.',
    30,
    30,
    20,
    20,
    10,
    5,
    5,
    5,
    500,
    0,
    0,
    1,
    0
);

-- Habilidades del Heroe
insert into habilidad values(
	1,
	'Proyectil Magico',
	'Disparas chispas magicas de tus manos.',
	2,
    4,
    'ofensivo',
    1
);

insert into habilidad values(
	2,
	'Flecha Helada',
	'Lanzas una flecha que congela todo a su paso.',
	3,
    6,
    'ofensivo',
    1
);

insert into habilidad values(
	3,
	'Curar Heridas',
	'Sana las heridas superficiales.',
	5,
    6,
    'curativo',
    1
);

insert into objeto values(
	1,
	'Bomba Pequeña',
    'Inflige 25 puntos de daño.',
	25,
	2,
	'ofensivo',
    150,
    1
);

insert into objeto values(
	2,
	'Bomba Grande',
	'Inflige 60 puntos de daño.',
	60,
	1,
	'ofensivo',
    400,
    1
);

insert into objeto values(
	3,
	'Pocion de Mana',
	'Restablece 50 puntos de mana.',
	30,
	2,
	'curativo',
	250,
    1
);
